### ISSUE TITLE
Categories Only exist for certain years during model start_year and final_year

### ISSUE THREAD

**Issue by Craig44** [alistairdunn1/CASAL2#110]

**Comment by Zaita** [comment]
@alistairdunn1 
When a category is specified in multiple lookups do we want to
1. Error out
2. Add the years from each and error if they're duplicates
3. Add the years from each and ignore duplicates
4. Clear the years on each lookup so that it is the last rule that is implemented only (similar to a firewall)

e.g.
@categories
format sex.stage
names male,female.immature,mature
years sex=male=2000 stage=mature=2001
^^ This is the actual syntax

**Comment by Zaita** [comment]
@doonanij @largek

**Comment by Zaita** [comment]
Implemented
